language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
matrix:
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

install:
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install notebook
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - coverage run --source=. -m py.test -s tests/
after_success:
  - coverage report -m
  - codecov
