language: python
python:
  - "3.6"
  - "pypy"
  - "2.7"
  - "3.4"
  - "3.5"
matrix:
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

install:
  # command to install dependencies
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  # install is required for testing the pre-commit mode
  - pip install .
  # install black if available (Python 3.6 and above), and autopep8 for testing the pipe mode
  - pip install black || true
  - pip install autopep8 || true
  # install sphinx_gallery and matplotlib if available (may not work on pypy)
  - pip install sphinx_gallery || true
  # download and install pandoc 2.7.2
  - wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-linux.tar.gz
  - tar xvzf pandoc-2.7.2-linux.tar.gz
  - export PATH=pandoc-2.7.2/bin:$PATH
  - pandoc -v
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --statistics
script:
  - coverage run --source=. -m py.test
after_success:
  - coverage report -m
  - codecov
